
fips_to_st = {
    '01': ('AL', 'Alabama'),
    '02': ('AK', 'Alaska'),
    '04': ('AZ', 'Arizona'),
    '05': ('AR', 'Arkansas'),
    '06': ('CA', 'California'),
    '08': ('CO', 'Colorado'),
    '09': ('CT', 'Connecticut'),
    '10': ('DE', 'Delaware'),
    '11': ('DC', 'District of Columbia'),
    '12': ('FL', 'Florida'),
    '13': ('GA', 'Georgia'),
    '15': ('HI', 'Hawaii'),
    '16': ('ID', 'Idaho'),
    '17': ('IL', 'Illinois'),
    '18': ('IN', 'Indiana'),
    '19': ('IA', 'Iowa'),
    '20': ('KS', 'Kansas'),
    '21': ('KY', 'Kentucky'),
    '22': ('LA', 'Louisiana'),
    '23': ('ME', 'Maine'),
    '24': ('MD', 'Maryland'),
    '25': ('MA', 'Massachusetts'),
    '26': ('MI', 'Michigan'),
    '27': ('MN', 'Minnesota'),
    '28': ('MS', 'Mississippi'),
    '29': ('MO', 'Missouri'),
    '30': ('MT', 'Montana'),
    '31': ('NE', 'Nebraska'),
    '32': ('NV', 'Nevada'),
    '33': ('NH', 'New Hampshire'),
    '34': ('NJ', 'New Jersey'),
    '35': ('NM', 'New Mexico'),
    '36': ('NY', 'New York'),
    '37': ('NC', 'North Carolina'),
    '38': ('ND', 'North Dakota'),
    '39': ('OH', 'Ohio'),
    '40': ('OK', 'Oklahoma'),
    '41': ('OR', 'Oregon'),
    '42': ('PA', 'Pennsylvania'),
    '44': ('RI', 'Rhode Island'),
    '45': ('SC', 'South Carolina'),
    '46': ('SD', 'South Dakota'),
    '47': ('TN', 'Tennessee'),
    '48': ('TX', 'Texas'),
    '49': ('UT', 'Utah'),
    '50': ('VT', 'Vermont'),
    '51': ('VA', 'Virginia'),
    '53': ('WA', 'Washington'),
    '54': ('WV', 'West Virginia'),
    '55': ('WI', 'Wisconsin'),
    '56': ('WY', 'Wyoming')
}

st_to_fips = {
    'AL': '01',
    'AK': '02',
    'AZ': '04',
    'AR': '05',
    'CA': '06',
    'CO': '08',
    'CT': '09',
    'DE': '10',
    'DC': '11',
    'FL': '12',
    'GA': '13',
    'HI': '15',
    'ID': '16',
    'IL': '17',
    'IN': '18',
    'IA': '19',
    'KS': '20',
    'KY': '21',
    'LA': '22',
    'ME': '23',
    'MD': '24',
    'MA': '25',
    'MI': '26',
    'MN': '27',
    'MS': '28',
    'MO': '29',
    'MT': '30',
    'NE': '31',
    'NV': '32',
    'NH': '33',
    'NJ': '34',
    'NM': '35',
    'NY': '36',
    'NC': '37',
    'ND': '38',
    'OH': '39',
    'OK': '40',
    'OR': '41',
    'PA': '42',
    'RI': '44',
    'SC': '45',
    'SD': '46',
    'TN': '47',
    'TX': '48',
    'UT': '49',
    'VT': '50',
    'VA': '51',
    'WA': '53',
    'WV': '54',
    'WI': '55',
    'WY': '56'
}

